# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev_doctest',
                'doc_host': 'https://omlnaut.github.io',
                'git_url': 'https://github.com/omlnaut/nbdev_doctest',
                'lib_path': 'nbdev_doctest'},
  'syms': {'nbdev_doctest.core': {'nbdev_doctest.core.foo': ('core.html#foo', 'nbdev_doctest/core.py')}}}